spring:
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp

logging:
  level:
      kr.tinywind: TRACE
      org.springframework: INFO
      org.hibernate: INFO
      org.h2: INFO

server:
    error:
        whitelabel:
            enabled: false
